import React, { useState, useEffect, useRef } from 'react';
import { PhoneFrame } from '../phone/PhoneFrame';
import { ButtonPlate, type AppPage } from './ButtonPlate';

import { MeetingsListView } from '../views/MeetingsListView';
import { LiveRecordingView } from '../views/LiveRecordingView';
import { MeetingDetailView } from '../views/MeetingDetailView';
import { GlobalActionsView } from '../views/GlobalActionsView';
import { NewMeetingModal } from '../views/NewMeetingModal';
import { useRecordingSession } from '../../hooks/useRecordingSession';
import type { SessionState, MeetingSummary, MeetingInfo } from '../../types/transcription';
import { updateMeetingInfo } from '../../services/api';
import { FileText, Plus, AlertTriangle } from 'lucide-react';
import { VerbaLogo } from '../common/VerbaLogo';

const LOCAL_STORAGE_KEY = 'verba_meetings_v1';

const PAGE_ORDER: Record<string, number> = {
  meetings: 0,
  transcript: 1,
  summary: 1,
  actions: 2,
  live: 3,
};

const todayString = () =>
  new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });

const DEFAULT_MEETING_INFO: MeetingInfo = {
  title: '',
  meeting_date: todayString(),
  meeting_type: 'Team Meeting',
  location: '',
  organizer: '',
  participants: [],
};

export const MainLayout: React.FC = () => {
  const {
    sessionId,
    status,
    processingStage,
    languageMode,
    liveTranscript,
    interimText,
    finalTranscript,
    summary,
    recordingSeconds,
    isPaused,
    analyserNode,
    errorMessage,
    startSession,
    pauseRecording,
    resumeRecording,
    stopSession,
    toggleActionItem,
    renameSpeaker,
    exportSession,
  } = useRecordingSession();

  // Active page state for universal navigation
  const [activePage, setActivePage] = useState<AppPage>('meetings');
  const [navDirection, setNavDirection] = useState<'forward' | 'backward' | 'up' | 'fade'>('fade');

  // Meeting setup state
  const [activeMeetingInfo, setActiveMeetingInfo] = useState<MeetingInfo>(DEFAULT_MEETING_INFO);
  const [isNewMeetingModalOpen, setIsNewMeetingModalOpen] = useState(false);
  // Guards an in-flight recording/processing session against accidental replacement
  const [confirmNewMeetingWhileActive, setConfirmNewMeetingWhileActive] = useState(false);

  const navigateTo = (newPage: AppPage, customDir?: 'forward' | 'backward' | 'up' | 'fade') => {
    if (newPage === activePage) return;

    let dir: 'forward' | 'backward' | 'up' | 'fade' = customDir || 'fade';
    if (!customDir) {
      if (newPage === 'live') {
        dir = 'up';
      } else if (activePage === 'live') {
        dir = 'backward';
      } else {
        const fromIdx = PAGE_ORDER[activePage] ?? 0;
        const toIdx = PAGE_ORDER[newPage] ?? 0;
        dir = toIdx > fromIdx ? 'forward' : toIdx < fromIdx ? 'backward' : 'fade';
      }
    }

    setNavDirection(dir);

    if (typeof document !== 'undefined' && 'startViewTransition' in document) {
      (document as any).startViewTransition(() => {
        setActivePage(newPage);
      });
    } else {
      setActivePage(newPage);
    }
  };

  const [sessions, setSessions] = useState<SessionState[]>(() => {
    try {
      const saved = localStorage.getItem(LOCAL_STORAGE_KEY);
      return saved ? JSON.parse(saved) : [];
    } catch {
      return [];
    }
  });
  const [selectedSession, setSelectedSession] = useState<SessionState | null>(null);

  // Resolved session for detail pages (falls back to the most recent one)
  const effectiveSession = selectedSession || (sessions.length > 0 ? sessions[0] : null);

  // Sync with backend sessions on mount
  useEffect(() => {
    fetch('/api/sessions')
      .then((res) => (res.ok ? res.json() : []))
      .then((backendSessions: SessionState[]) => {
        if (backendSessions && backendSessions.length > 0) {
          setSessions((prev) => {
            const map = new Map<string, SessionState>();
            prev.forEach((s) => map.set(s.id, s));
            backendSessions.forEach((s) => map.set(s.id, s));
            const merged = Array.from(map.values());
            try {
              localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(merged));
            } catch {}
            return merged;
          });
        }
      })
      .catch((err) => console.log('Backend sync:', err));
  }, []);

  // Save sessions to localStorage
  useEffect(() => {
    try {
      localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(sessions));
    } catch {}
  }, [sessions]);

  // When recording status becomes 'recording', navigate to 'live'
  useEffect(() => {
    if (status === 'recording') {
      savedCompleteRef.current = null;
      navigateTo('live', 'up');
    }
  }, [status]);

  // When post-recording processing finishes, save the session and STAY on the
  // Record view. The summary is generated by the backend pipeline; exports are
  // available from the Record page at any time.
  const savedCompleteRef = useRef<string | null>(null);
  useEffect(() => {
    if (status === 'complete' && sessionId && savedCompleteRef.current !== sessionId) {
      savedCompleteRef.current = sessionId;
      const now = new Date();
      const timeStr = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

      const finalSessionSummary: MeetingSummary = summary || {
        executive_summary: liveTranscript.length > 0
          ? liveTranscript.map((t) => t.text).join(' ')
          : 'Audio recording captured and processed.',
        key_points: ['Session recorded and transcribed successfully.'],
        decisions: [],
        action_items: [],
        questions: [],
        speaker_contributions: [],
      };

      const meetingTitle =
        activeMeetingInfo.title.trim() || `Meeting · ${activeMeetingInfo.meeting_date || todayString()}`;

      const newSession: SessionState = {
        id: sessionId || `session_${Date.now()}`,
        title: meetingTitle,
        status: 'complete',
        started_at: `Today at ${timeStr}`,
        ended_at: timeStr,
        duration_seconds: recordingSeconds || 1,
        language_mode: languageMode,
        live_transcript: liveTranscript,
        final_transcript: finalTranscript || undefined,
        summary: finalSessionSummary,
        meeting_info: { ...activeMeetingInfo, title: meetingTitle },
        speaker_names: {},
      };

      // Persist meeting info to the backend session
      if (sessionId) {
        updateMeetingInfo(sessionId, newSession.meeting_info)
          .then((updated) => {
            setSessions((prev) => {
              const exists = prev.some((s) => s.id === updated.id);
              return exists
                ? prev.map((s) => (s.id === updated.id ? updated : s))
                : [newSession, ...prev];
            });
            setSelectedSession((prev) => (prev && prev.id === updated.id ? updated : prev));
          })
          .catch((err) => console.warn('Meeting info update:', err));
      }

      setSessions((prev) => {
        const exists = prev.some((s) => s.id === newSession.id);
        return exists ? prev.map((s) => (s.id === newSession.id ? newSession : s)) : [newSession, ...prev];
      });
      setSelectedSession(newSession);
    }
  }, [status, sessionId, summary, liveTranscript, finalTranscript, recordingSeconds, languageMode, activeMeetingInfo]);

  // Opening the "New Meeting" modal while a session is live must not silently
  // kill the recording. Route through a confirmation that keeps the mic streaming
  // until the user explicitly chooses to stop.
  const handleRequestNewMeeting = () => {
    if (status === 'recording' || status === 'processing') {
      setConfirmNewMeetingWhileActive(true);
      return;
    }
    setIsNewMeetingModalOpen(true);
  };

  const handleStartMeetingWithInfo = (info: MeetingInfo) => {
    setActiveMeetingInfo(info);
    startSession(languageMode);
    navigateTo('live', 'up');
  };

  const handleSaveMeetingInfo = (info: MeetingInfo) => {
    setActiveMeetingInfo(info);
    if (effectiveSession) {
      updateMeetingInfo(effectiveSession.id, info)
        .then((updated) => {
          setSessions((prev) => prev.map((s) => (s.id === updated.id ? updated : s)));
          setSelectedSession(updated);
        })
        .catch((err) => console.warn('Meeting info update:', err));
    }
  };

  const handleStopRecording = () => {
    stopSession();
  };

  const handleSelectMeeting = (session: SessionState) => {
    setSelectedSession(session);
    if (session.meeting_info) {
      setActiveMeetingInfo(session.meeting_info);
    }
    navigateTo('transcript', 'forward');
  };

  // Determine theme for current page
  const pageTheme = activePage === 'live' && status === 'recording' ? 'royal' : 'light';

  return (
    <div className="fixed inset-0 w-full h-full bg-[#F4F7F5] text-slate-900 flex flex-col overflow-hidden select-none selection:bg-[#008751]/30 font-sans">
      <a href="#main-content" className="sr-only focus:not-sr-only focus:absolute focus:top-2 focus:left-2 focus:z-[60] focus:bg-white focus:px-3 focus:py-2 focus:rounded-lg focus:text-xs focus:font-bold">
        Skip to content
      </a>
      {/* Subtle brand accent ribbon */}
      <div className="w-full h-1 bg-gradient-to-r from-emerald-600 via-[#008751] to-emerald-800 flex-shrink-0 z-50 no-print" />

      {/* Main Responsive App Body */}
      <main id="main-content" className="flex-1 min-h-0 w-full max-w-full sm:max-w-3xl md:max-w-4xl lg:max-w-5xl xl:max-w-6xl mx-auto flex flex-col overflow-hidden relative bg-[#F8FAF9] sm:border-x sm:border-emerald-900/10 sm:shadow-lg">
        {/* Floating Minimal Header Bar */}
        {activePage !== 'live' && (
          <div className="absolute top-2.5 left-3 right-3 sm:left-6 sm:right-6 z-40 no-print flex justify-center pointer-events-none">
            <header className="pointer-events-auto w-full max-w-4xl bg-white/92 hover:bg-white backdrop-blur-md border border-slate-200/90 shadow-[0_4px_20px_rgba(0,0,0,0.06)] rounded-2xl px-3 sm:px-4 py-2 flex items-center justify-between transition-all">
              {/* Left: Emblem & App Title */}
              <div
                onClick={() => navigateTo('meetings', 'backward')}
                className="flex items-center gap-2.5 cursor-pointer select-none active:scale-95 transition-all"
                title="View All Meetings"
              >
                <VerbaLogo size="sm" variant="full" lightMode={true} />
              </div>

              {/* Center: Active Meeting Badge */}
              <button
                onClick={() => handleRequestNewMeeting()}
                className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-slate-100 hover:bg-slate-200/80 border border-slate-200 text-[11px] font-semibold text-slate-800 transition-all cursor-pointer active:scale-95"
                title="Edit / Configure Meeting Information"
              >
                <FileText className="w-3 h-3 text-[#008751]" />
                <span className="truncate max-w-[120px] sm:max-w-[190px]">
                  {effectiveSession?.meeting_info?.title ||
                    activeMeetingInfo.title ||
                    activeMeetingInfo.meeting_type ||
                    'Set up meeting'}
                </span>
              </button>

              {/* Right: Actions */}
              <div className="flex items-center gap-2">
                <button
                  onClick={() => handleRequestNewMeeting()}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-[#008751] hover:bg-[#007043] text-white text-xs font-bold shadow-xs active:scale-95 transition-all cursor-pointer"
                  title="Configure & Record New Meeting"
                >
                  <Plus className="w-3.5 h-3.5" />
                  <span className="hidden sm:inline">New Meeting</span>
                  <span className="sm:hidden">New</span>
                </button>
              </div>
            </header>
          </div>
        )}

        {/* Main Mobile/Desktop App Container */}
        <PhoneFrame theme={pageTheme}>
          {/* Content Body Area with fluid directional motion */}
          <div
            key={activePage}
            className={`flex-1 min-h-0 flex flex-col overflow-hidden relative ${
              activePage !== 'live' ? 'pt-[76px] sm:pt-[82px]' : ''
            } ${
              navDirection === 'forward'
                ? 'page-enter-forward'
                : navDirection === 'backward'
                ? 'page-enter-backward'
                : navDirection === 'up'
                ? 'page-enter-up'
                : 'page-enter-fade'
            }`}
          >
            {/* 1. Meetings Page */}
            {activePage === 'meetings' && (
              <MeetingsListView
                sessions={sessions}
                onSelectMeeting={handleSelectMeeting}
                onStartRecord={() => handleRequestNewMeeting()}
              />
            )}

            {/* 2. Live Recording Page */}
            {activePage === 'live' && (
              <LiveRecordingView
                title={
                  status === 'recording'
                    ? 'Live Meeting Recording'
                    : status === 'processing'
                    ? 'Processing Recording'
                    : 'Audio Stream'
                }
                recordingSeconds={recordingSeconds}
                liveTranscript={liveTranscript}
                interimText={interimText}
                analyserNode={analyserNode}
                isPaused={isPaused}
                isProcessing={status === 'processing'}
                processingStage={processingStage}
                errorMessage={errorMessage}
                onPause={pauseRecording}
                onResume={resumeRecording}
                onMinimize={() => navigateTo('meetings', 'backward')}
                onStop={handleStopRecording}
                onViewTranscript={() => navigateTo('transcript', 'forward')}
                languageMode={languageMode}
              />
            )}

            {/* 3. Transcript Page */}
            {activePage === 'transcript' &&
              (effectiveSession ? (
                <MeetingDetailView
                  session={effectiveSession}
                  initialTab="summary"
                  onBack={() => navigateTo('meetings', 'backward')}
                  onToggleActionItem={toggleActionItem}
                  onExport={exportSession}
                  onRenameSpeaker={renameSpeaker}
                />
              ) : (
                <div className="flex-1 flex flex-col items-center justify-center p-6 text-center text-slate-500 space-y-3 bg-[#F8FAFC]">
                  <div className="w-14 h-14 rounded-full bg-slate-100 flex items-center justify-center text-slate-400">
                    <FileText className="w-7 h-7" />
                  </div>
                  <h3 className="text-base font-bold text-slate-900">No Transcript Yet</h3>
                  <p className="text-xs text-slate-500 max-w-xs leading-relaxed">
                    Record a meeting or select an existing session to inspect its speaker-diarized transcript and playback.
                  </p>
                  <button
                    onClick={() => handleRequestNewMeeting()}
                    className="px-4 py-2 rounded-full bg-[#008751] hover:bg-[#007043] text-white text-xs font-semibold shadow-md shadow-emerald-700/20 active:scale-95 transition-all flex items-center gap-1.5 cursor-pointer"
                  >
                    <Plus className="w-3.5 h-3.5" />
                    <span>New Meeting</span>
                  </button>
                </div>
              ))}

            {/* 4. Actions Page */}
            {activePage === 'actions' && (
              <GlobalActionsView
                sessions={sessions}
                onBack={() => navigateTo('meetings', 'backward')}
                onSelectMeeting={(session) => {
                  setSelectedSession(session);
                  navigateTo('transcript', 'forward');
                }}
                onStartRecord={() => handleRequestNewMeeting()}
              />
            )}
          </div>

          {/* Universal Floating Button Plate (Docked at bottom of ALL pages) */}
          <ButtonPlate
            activePage={activePage}
            onNavigate={(page) => navigateTo(page)}
            hasSession={Boolean(effectiveSession)}
            theme={pageTheme}
            isRecording={status === 'recording'}
            isProcessing={status === 'processing'}
          />
        </PhoneFrame>
      </main>

      {/* New Meeting Setup Modal */}
      <NewMeetingModal
        isOpen={isNewMeetingModalOpen}
        onClose={() => setIsNewMeetingModalOpen(false)}
        initialInfo={effectiveSession?.meeting_info || activeMeetingInfo}
        onStartMeeting={handleStartMeetingWithInfo}
        onSaveMeetingInfo={handleSaveMeetingInfo}
      />

      {/* Guard: opening setup while a session is live must be explicit */}
      {confirmNewMeetingWhileActive && (
        <div className="fixed inset-0 z-[70] flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm">
          <div className="bg-white rounded-2xl border border-slate-200 shadow-xl max-w-sm w-full p-5 space-y-4">
            <div className="flex items-start gap-3">
              <div className="w-9 h-9 rounded-xl bg-amber-50 text-amber-700 flex items-center justify-center flex-shrink-0 border border-amber-200/70">
                <AlertTriangle className="w-4.5 h-4.5" />
              </div>
              <div>
                <h3 className="text-sm font-bold text-slate-900">A session is active</h3>
                <p className="text-xs text-slate-500 mt-1 leading-relaxed">
                  Starting a new meeting will stop the current recording. You can also just view it from the Meetings list.
                </p>
              </div>
            </div>
            <div className="flex flex-col gap-2">
              <button
                onClick={() => {
                  setConfirmNewMeetingWhileActive(false);
                  stopSession();
                  setIsNewMeetingModalOpen(true);
                }}
                className="w-full px-4 py-2.5 rounded-xl bg-[#008751] hover:bg-[#007043] text-white text-xs font-bold active:scale-[0.99] transition-all cursor-pointer"
              >
                Stop current session &amp; start new
              </button>
              <button
                onClick={() => {
                  setConfirmNewMeetingWhileActive(false);
                  navigateTo('meetings', 'backward');
                }}
                className="w-full px-4 py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-bold active:scale-[0.99] transition-all cursor-pointer"
              >
                View Meetings instead
              </button>
              <button
                onClick={() => setConfirmNewMeetingWhileActive(false)}
                className="w-full px-4 py-2 rounded-xl text-slate-500 hover:text-slate-800 text-xs font-semibold cursor-pointer"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
